spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

app:
  jwt:
    secret: drdukyfkyuftrsrxcvjhguftfyuyfgfgcfgvnnvnbbnnklhuyuiihghfgdfdfxxc

